### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated

### ISSUE THREAD

**Issue by yhoiseth** [thiswayq/homebrew-versions-1#2]
Thanks a lot for making this tap. Much appreciated :)

I just ran `brew install thiswayq/homebrew-versions-1/elasticsearch17` on a pretty fresh install of Mac OS Sierra.

See output below. Note the warnings. It doesn't seem like this breaks anything (yet).

```
Updating Homebrew...
==> Installing elasticsearch17 from thiswayq/versions-1
==> Downloading https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.tar.gz
######################################################################## 100.0%
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:72:in `caveats'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:72:in `caveats'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/thiswayq/homebrew-versions-1/elasticsearch17.rb:106:in `plist'
Please report this to the thiswayq/versions-1 tap!

==> Caveats
Data:    /usr/local/var/elasticsearch/elasticsearch_yngve/
Logs:    /usr/local/var/log/elasticsearch/elasticsearch_yngve.log
Plugins: /usr/local/var/lib/elasticsearch/plugins/
Config:  /usr/local/etc/elasticsearch/

To have launchd start thiswayq/versions-1/elasticsearch17 now and restart at login:
  brew services start thiswayq/versions-1/elasticsearch17
Or, if you don't want/need a background service you can just run:
  elasticsearch --config=/usr/local/opt/elasticsearch17/config/elasticsearch.yml
==> Summary
🍺  /usr/local/Cellar/elasticsearch17/1.7.6: 38 files, 29.7MB, built in 11 seconds
```

**Comment by tom10271** [comment]
`brew install rentziass/homebrew-versions-1/elasticsearch17`

If you really just wanted to install it and don't care about the rest for now

**Comment by thiswayq** [comment]
Pr containing fix is merged, sorry for the delay, i didn't notice this repository actually got that attention.
